title: Ragini Mangla
description: A portfolio showcasing my work and experience.
theme: just-the-docs

url: https://raginimangla.github.io/aboutme/

aux_links:
  Github Repository: https://github.com/raginimangla/aboutme

heading_anchors: true
